/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simple.proto */

#ifndef PROTOBUF_C_simple_2eproto__INCLUDED
#define PROTOBUF_C_simple_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SimpleMessage SimpleMessage;


/* --- enums --- */


/* --- messages --- */

struct  _SimpleMessage {
    ProtobufCMessage base;
    int32_t lucky_number;
};
#define SIMPLE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&simple_message__descriptor) \
    , 0 }


/* SimpleMessage methods */
void   simple_message__init
(SimpleMessage         *message);
size_t simple_message__get_packed_size
(const SimpleMessage   *message);
size_t simple_message__pack
(const SimpleMessage   *message,
 uint8_t             *out);
size_t simple_message__pack_to_buffer
(const SimpleMessage   *message,
 ProtobufCBuffer     *buffer);
SimpleMessage *
simple_message__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data);
void   simple_message__free_unpacked
(SimpleMessage *message,
 ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SimpleMessage_Closure)
(const SimpleMessage *message,
 void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor simple_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_simple_2eproto__INCLUDED */
